version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - ${WORDPRESS_PORT}:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: db
      WORDPRESS_DB_PASSWORD: db
      WORDPRESS_DB_NAME: db
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_ROOT_PASSWORD: db
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer:4.7.7-standalone
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9091:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: db

volumes:
  wordpress:
  db:

