version: '3.1'

services:
  db:
    image: postgres:13.1
    restart: always
    evironment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
  
  adminer:
    image: adminer:4.7.7-standalone
    restart: always
    ports:
      - ${ADMINER_PORT}:8080


