version: '3.1'

services:

  #wordpress:
  #  depends_on:
  #    - db
  #  image: wordpress
  #  restart: always
  #  ports:
  #    - ${WORDPRESS_PORT}:80
  #  environment:
  #    WORDPRESS_DB_HOST: db
  #    WORDPRESS_DB_USER: db
  #    WORDPRESS_DB_PASSWORD: db
  #    WORDPRESS_DB_NAME: db
  #  volumes:
  #    - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306 #${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: db #${DB_HOST}
      MYSQL_USER: db #${DB_USER}
      MYSQL_PASSWORD: db #${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: db #${DB_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  adminer:
    depends_on:
      - db
    image: adminer:4.7.7-standalone
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: db

volumes:
  #wordpress:
  db:

